// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDWPeJ3mj2NNlbxrYuvNBYacWRwbiC1k',
    appId: '1:680338742855:web:0f5711f29c38103f149b62',
    messagingSenderId: '680338742855',
    projectId: 'pruebamovil-ed6e3',
    authDomain: 'pruebamovil-ed6e3.firebaseapp.com',
    storageBucket: 'pruebamovil-ed6e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1k6plMbSxTuOran8zATLJ1Y49Q_AWdTs',
    appId: '1:680338742855:android:894cf4f3d5ad7b7c149b62',
    messagingSenderId: '680338742855',
    projectId: 'pruebamovil-ed6e3',
    storageBucket: 'pruebamovil-ed6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdeyTGZ8r7Jf7nvhsK6nJ45Hj_0rwPVqk',
    appId: '1:680338742855:ios:36d34824b07d8940149b62',
    messagingSenderId: '680338742855',
    projectId: 'pruebamovil-ed6e3',
    storageBucket: 'pruebamovil-ed6e3.firebasestorage.app',
    iosBundleId: 'com.example.pruebamovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdeyTGZ8r7Jf7nvhsK6nJ45Hj_0rwPVqk',
    appId: '1:680338742855:ios:36d34824b07d8940149b62',
    messagingSenderId: '680338742855',
    projectId: 'pruebamovil-ed6e3',
    storageBucket: 'pruebamovil-ed6e3.firebasestorage.app',
    iosBundleId: 'com.example.pruebamovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDDWPeJ3mj2NNlbxrYuvNBYacWRwbiC1k',
    appId: '1:680338742855:web:f6907f7b2f445847149b62',
    messagingSenderId: '680338742855',
    projectId: 'pruebamovil-ed6e3',
    authDomain: 'pruebamovil-ed6e3.firebaseapp.com',
    storageBucket: 'pruebamovil-ed6e3.firebasestorage.app',
  );

}